### ISSUE TITLE
Different approach to integrate with UPM

### ISSUE THREAD

**Issue by bdovaz** [microsoft/MSBuildForUnity#131]
There is [a Unity employee](https://xoofx.com/) who has externally developed a server-side integration into ASP .NET Core that converts Nuget packages into Unity's package format:

https://github.com/xoofx/UnityNuGet 

You haven't talked to him at all? I think his solution is much better because it could be integrated with Unity's Asset Store publishers.

Keep in mind that Unity is working on allowing anyone who publishes a package in the store to use the UPM format and since Unity supports .NET Standard 2.0 it is more common to see Nuget dependencies.

Until now these dependencies have been copied directly (the *.dll files) to the developer's package but ideally they should be managed through dependencies in the package.json file

https://docs.unity3d.com/Manual/upm-manifestPkg.html

Otherwise there may be multiple publishers including the same package in *.dll format and triggering a difficult conflict to resolve without having to modify the source code of the publisher's package manually.

**Comment by ryantrem** [comment]
Yes, we are aware of this project, and we did briefly chat with Alexandre before we started this project. That approach did not meet our needs for several reasons:
1. Having a curated list is hard to scale up, particularly for frequently changing dependencies.
1. We needed support for TFMs beyond netstandard2.0.
1. NuGet packages that include custom props/targets are providing build time logic, not just a zip file with dlls. These need to be installed in the context of MSBuild.
1. UPM is not helpful for cross-engine projects. In these cases, we may have library interfaces that are engine-agnostic, with engine-specific implementations. In these cases, Unity dependencies are implementation details, and you can have engine-agnostic layers on top of engine-specific implementations (that have engine-agnostic interfaces). For this to work, you need an engine-agnostic packaging solution, so NuGet provides a better option than UPM.

**Comment by bdovaz** [comment]
@ryantrem So then how can we achieve the following case?

Suppose I have my custom packages (UPM packages in {project_root}/Packages) that want to use each of one different or same nuget packages on different versions. Will I be able to integrate this on each package (a *.csproj or the files that are needed) and be able to resolve version conflicts on the project that uses this UPM packages with this nuget dependencies?

I think you need to create an example of this because as you know, all goes for UPM packages so it has to work.
