### ISSUE TITLE
Doesn't work with projects with spaces in the name

### ISSUE THREAD

**Issue by rgonzalezVW** [microsoft/MSBuildForUnity#132]
If the Unity project has spaces in the name, or the added csproj files contains spaces, it's unable to compile the projects.
For example, if I create a project with the default Unity name "New Unity Project", the resulting compile command line is "C:\Program Files\dotnet\dotnet.exe msbuild New Unity Project.Dependencies.msb4u.csproj -restore  -v:minimal -p:NuGetInteractive=true  -t:Build -p:Configuration=Release", which causes "MSBUILD : error MSB1008: Only one project can be specified.".
Adding quotes around the project name should solve this issue.

**Comment by mgrman** [comment]
This is a problem for us as well. Our setup requires space in product name. Is this something planned to fix?
