### ISSUE TITLE
Getting "Unable to find package Microsoft.Build.NoTargets" and "error MSB4236: The SDK 'Microsoft.Build.NoTargets/1.0.85' specified could not be found."

### ISSUE THREAD

**Issue by aybe** [microsoft/MSBuildForUnity#153]
I've been trying the following scenario:

https://github.com/microsoft/MSBuildForUnity/blob/master/Documentation/CoreScenarios.md#scenario-2-share-c-library-between-unity-projects

These are the errors I'm getting:

```
C:\Users\Aybe\source\repos\Spilskinanke\MSBuild\Projects\Spilskinanke.Dependencies.msb4u.g.props(22,3): error : Unable to find package Microsoft.Build.NoTargets. No packages exist with this id in source(s): MSBuildForUnity
UnityEngine.Debug:LogError (object)
Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage (string,Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:385)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass13_0:<BuildProjects>b__1 (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:213)
Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>>:Report (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass14_0:<BuildProjectsAsync>b__1 (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:330)
Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>:Report (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0 (object,System.Diagnostics.DataReceivedEventArgs) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:462)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

```
C:\Users\Aybe\source\repos\Spilskinanke\MSBuild\Projects\Spilskinanke.Dependencies.msb4u.g.props(22,31): error MSB4236: The SDK 'Microsoft.Build.NoTargets/1.0.85' specified could not be found. [C:\Users\Aybe\source\repos\Spilskinanke\Assets\Spilskinanke.Dependencies.msb4u.csproj]
UnityEngine.Debug:LogError (object)
Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage (string,Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:385)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass13_0:<BuildProjects>b__1 (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:213)
Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>>:Report (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass14_0:<BuildProjectsAsync>b__1 (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:330)
Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>:Report (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0 (object,System.Diagnostics.DataReceivedEventArgs) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.2-20211109.1/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:462)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

**Comment by jieseattle** [comment]
Same issue.
C:\Users\opal\Desktop\azure-object-anchors\quickstarts\apps\unity\mrtk\Assets> C:\Program Files\dotnet\dotnet.exe msbuild AOAMRTKApp.Dependencies.msb4u.csproj -restore  -v:minimal -p:NuGetInteractive=true  -t:Build -p:Configuration=Release
C:\Users\opal\Desktop\azure-object-anchors\quickstarts\apps\unity\mrtk\MSBuild\Projects\AOAMRTKApp.Dependencies.msb4u.g.props(22,3): error : Unable to find package Microsoft.Build.NoTargets. No packages exist with this id in source(s): MSBuildForUnity
0x00007ff7b9bc809c (Unity) StackWalker::GetCurrentCallstack
0x00007ff7b9bd0739 (Unity) StackWalker::ShowCallstack
0x00007ff7bb105eec (Unity) GetStacktrace
0x00007ff7bc23a5a3 (Unity) DebugStringToFile
0x00007ff7b9cb25c6 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000024a20ba5ccb (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000024a20ba5c1b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000024a20ba59a0 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000024a20bac435 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x0000024a20bac3ab (Mono JIT Code) [MSBuildProjectBuilder.cs:386] Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage (string,Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType) 
0x0000024a20ba4363 (Mono JIT Code) [MSBuildProjectBuilder.cs:216] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass13_0:<BuildProjects>b__1 (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) 
0x0000024a20ba42c6 (Mono JIT Code) [MSBuildProjectBuilder.cs:516] Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>>:Report (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) 
0x0000024a20ba4219 (Mono JIT Code) [MSBuildProjectBuilder.cs:330] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass14_0:<BuildProjectsAsync>b__1 (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) 
0x0000024a20ba415e (Mono JIT Code) [MSBuildProjectBuilder.cs:516] Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>:Report (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) 
0x0000024a20bac21b (Mono JIT Code) [MSBuildProjectBuilder.cs:464] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0 (object,System.Diagnostics.DataReceivedEventArgs) 
0x00000249fcc7aee2 (Mono JIT Code) System.Diagnostics.Process:OutputReadNotifyUser (string)
0x00000249fcc7a689 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:FlushMessageQueue ()
0x00000249fcc799bb (Mono JIT Code) System.Diagnostics.AsyncStreamReader:GetLinesFromStringBuilder ()
0x00000249fcc77c93 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:ReadBuffer (System.IAsyncResult)
0x00000249fcc76ff0 (Mono JIT Code) System.IO.Stream/ReadWriteTask:InvokeAsyncCallback (object)
0x00000249fb703dfe (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000249fb703aab (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000249fcc76f1b (Mono JIT Code) System.IO.Stream/ReadWriteTask:System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task)
0x00000249fbaf97fc (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x00000249fbaf9543 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x00000249fbaf90eb (Mono JIT Code) System.Threading.Tasks.Task:FinishStageTwo ()
0x00000249fbaf8dbb (Mono JIT Code) System.Threading.Tasks.Task:Finish (bool)
0x00000249fbaf2fdb (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x00000249fbaf29cb (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x00000249fbaf274b (Mono JIT Code) System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
0x00000249fb7009e2 (Mono JIT Code) System.Threading.ThreadPoolWorkQueue:Dispatch ()
0x00000249fb70018b (Mono JIT Code) System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
0x00000249fcc89abd (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool (object,intptr,intptr,intptr)
0x00007ffdc7d2f200 (mono-2.0-bdwgc) [mini-runtime.c:2849] mono_jit_runtime_invoke 
0x00007ffdc7cb2ac2 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007ffdc7cda381 (mono-2.0-bdwgc) [threadpool.c:366] worker_callback 
0x00007ffdc7cdca01 (mono-2.0-bdwgc) [threadpool-worker-default.c:499] worker_thread 
0x00007ffdc7cd6be8 (mono-2.0-bdwgc) [threads.c:1068] start_wrapper_internal 
0x00007ffdc7cd6976 (mono-2.0-bdwgc) [threads.c:1127] start_wrapper 
0x00007ffdf49f4ed0 (KERNEL32) BaseThreadInitThunk
0x00007ffdf5dae39b (ntdll) RtlUserThreadStart

C:\Users\opal\Desktop\azure-object-anchors\quickstarts\apps\unity\mrtk\MSBuild\Projects\AOAMRTKApp.Dependencies.msb4u.g.props(22,31): error MSB4236: The SDK 'Microsoft.Build.NoTargets/1.0.85' specified could not be found. [C:\Users\opal\Desktop\azure-object-anchors\quickstarts\apps\unity\mrtk\Assets\AOAMRTKApp.Dependencies.msb4u.csproj]
0x00007ff7b9bc809c (Unity) StackWalker::GetCurrentCallstack
0x00007ff7b9bd0739 (Unity) StackWalker::ShowCallstack
0x00007ff7bb105eec (Unity) GetStacktrace
0x00007ff7bc23a5a3 (Unity) DebugStringToFile
0x00007ff7b9cb25c6 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x0000024a20ba5ccb (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x0000024a20ba5c1b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x0000024a20ba59a0 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x0000024a20bac435 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x0000024a20bac3ab (Mono JIT Code) [MSBuildProjectBuilder.cs:386] Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage (string,Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType) 
0x0000024a20ba4363 (Mono JIT Code) [MSBuildProjectBuilder.cs:216] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass13_0:<BuildProjects>b__1 (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) 
0x0000024a20ba42c6 (Mono JIT Code) [MSBuildProjectBuilder.cs:516] Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>>:Report (System.ValueTuple`2<int, System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>) 
0x0000024a20ba4219 (Mono JIT Code) [MSBuildProjectBuilder.cs:330] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass14_0:<BuildProjectsAsync>b__1 (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) 
0x0000024a20ba415e (Mono JIT Code) [MSBuildProjectBuilder.cs:516] Microsoft.Build.Unity.MSBuildProjectBuilder/DelegateProgress`1<System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>>:Report (System.ValueTuple`2<string, Microsoft.Build.Unity.MSBuildProjectBuilder/ProgressMessageType>) 
0x0000024a20bac21b (Mono JIT Code) [MSBuildProjectBuilder.cs:464] Microsoft.Build.Unity.MSBuildProjectBuilder/<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0 (object,System.Diagnostics.DataReceivedEventArgs) 
0x00000249fcc7aee2 (Mono JIT Code) System.Diagnostics.Process:OutputReadNotifyUser (string)
0x00000249fcc7a689 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:FlushMessageQueue ()
0x00000249fcc799bb (Mono JIT Code) System.Diagnostics.AsyncStreamReader:GetLinesFromStringBuilder ()
0x00000249fcc77c93 (Mono JIT Code) System.Diagnostics.AsyncStreamReader:ReadBuffer (System.IAsyncResult)
0x00000249fcc76ff0 (Mono JIT Code) System.IO.Stream/ReadWriteTask:InvokeAsyncCallback (object)
0x00000249fb703dfe (Mono JIT Code) System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000249fb703aab (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
0x00000249fcc76f1b (Mono JIT Code) System.IO.Stream/ReadWriteTask:System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task)
0x00000249fbaf97fc (Mono JIT Code) System.Threading.Tasks.Task:FinishContinuations ()
0x00000249fbaf9543 (Mono JIT Code) System.Threading.Tasks.Task:FinishStageThree ()
0x00000249fbaf90eb (Mono JIT Code) System.Threading.Tasks.Task:FinishStageTwo ()
0x00000249fbaf8dbb (Mono JIT Code) System.Threading.Tasks.Task:Finish (bool)
0x00000249fbaf2fdb (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x00000249fbaf29cb (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x00000249fbaf274b (Mono JIT Code) System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
0x00000249fb7009e2 (Mono JIT Code) System.Threading.ThreadPoolWorkQueue:Dispatch ()
0x00000249fb70018b (Mono JIT Code) System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
0x00000249fcc89abd (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_bool (object,intptr,intptr,intptr)
0x00007ffdc7d2f200 (mono-2.0-bdwgc) [mini-runtime.c:2849] mono_jit_runtime_invoke 
0x00007ffdc7cb2ac2 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007ffdc7cda381 (mono-2.0-bdwgc) [threadpool.c:366] worker_callback 
0x00007ffdc7cdca01 (mono-2.0-bdwgc) [threadpool-worker-default.c:499] worker_thread 
0x00007ffdc7cd6be8 (mono-2.0-bdwgc) [threads.c:1068] start_wrapper_internal 
0x00007ffdc7cd6976 (mono-2.0-bdwgc) [threads.c:1127] start_wrapper 
0x00007ffdf49f4ed0 (KERNEL32) BaseThreadInitThunk
0x00007ffdf5dae39b (ntdll) RtlUserThreadStart

**Comment by RyanMilligan** [comment]
I ran into this as well while trying to get a project configured to use my shared library. It took a bunch of digging, but it appears to be caused by two problems:
1. Using an SDK other than .NET Core 2.1
2. Not using the globally configured NuGet packages
3. Never having restored a properly configured project that references the Microsoft.Build.NoTargets SDK

You can fix these issues with the following steps:

1. Open Assets\NuGet.config and comment out the `<clear />` line
2. Add a global.json to a folder at or above the Unity project with the following contents: 
```json {
  "sdk": {
    "version": "2.1.202"
  }
}
3. In Unity, click MSBuild -> Build All Projects

At this point, the project should build successfully without errors. Now that the SDK is safely downloaded to your local NuGet cache, you can delete global.json and put the `<clear />` line back, and all should be well going forward on that machine. I'm not 100% sure that switching to the .NET Core SDK was actually necessary, so if someone could try just steps 1 and 3 and update here whether it worked or not, that would be much appreciated.
