### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by storms-lab** [microsoft/MSBuildForUnity#154]
I really like what this project was trying to achieve and would like to use it in our workflow, but I am concerned about introducing a third-party tool on which we build our packaging workflow if it is not being maintained. Is it still being maintained? Or is there a better way to go about having a Unity project or UPM package depend on NuGet packages?

**Comment by KuraiAndras** [comment]
Right now the best solution I found is https://github.com/xoofx/UnityNuGet/

**Comment by bddckr** [comment]
See #142.

**Comment by jwittner** [comment]
Yes, we're still watching it, but not actively contributing new features. You could also try [NuGetForUnity](https://github.com/GlitchEnzo/NuGetForUnity/) if you're looking to take nuget package dependencies from your Unity project.
