### ISSUE TITLE
Allow generating projects for .NET Framework 4.6+ on Unity versions that support it

### ISSUE THREAD

**Issue by lynzrand** [microsoft/MSBuildForUnity#165]
On Unity versions that supports .NET Framework version higher than 4.6 (e.g. 2021.3 LTS, which supports .NET Framework 4.8), the generated `MSBuildForUnity.Common.props` file still uses the `net46` target. This prevents dependencies that use `netstandard2.0` target from being imported into the project.

```xml
  <PropertyGroup Condition="'$(MSBuildForUnityVersion)'==''">
    <MSBuildForUnityVersion>0.9.2</MSBuildForUnityVersion>
    
    <MSBuildForUnityPlatformPropsDirectory>$(_MSBuildForUnityGeneratedOutputDirectory)\Projects</MSBuildForUnityPlatformPropsDirectory>
    <MSBuildForUnityBuildOutputDirectory>$(_MSBuildForUnityGeneratedOutputDirectory)\Output</MSBuildForUnityBuildOutputDirectory>
    <MSBuildForUnityPublishDirectory>$(_MSBuildForUnityGeneratedOutputDirectory)\Publish</MSBuildForUnityPublishDirectory>
    
    <MSBuildForUnityDefaultOutputPath>$(UnityProjectAssetsPath)\Dependencies</MSBuildForUnityDefaultOutputPath>
    
    <UnityCurrentPlatform>WindowsStandalone64</UnityCurrentPlatform>

	<!-- HERE -->
    <UnityCurrentTargetFramework>net46</UnityCurrentTargetFramework>
	<!--      -->
    
    <UnityMajorVersion>2021</UnityMajorVersion>
    <UnityMinorVersion>3</UnityMinorVersion>
    <UnityEditorInstallPath>[...]\Unity\2021.3.11f1\Editor</UnityEditorInstallPath>
  </PropertyGroup>
```

Manually changing this value to `net48` seems to fix the problem.

## Potential causes

A quick search for `net46` brings me to this file: 

https://github.com/microsoft/MSBuildForUnity/blob/2fbb2569538c7c607a90ffc477e0405a2a721ee5/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/TargetFramework.cs#L33-L53

Maybe an additional Unity version check is needed to support Unity version that supports higher .NET Framework versions.

**Comment by jwittner** [comment]
Seems like a good addition - #164 added support for .Net 2.1 recently, perhaps a similar change is all you'd need?

**Comment by lynzrand** [comment]
Yes, I think a similar change is all we need.

**Comment by conmilo** [comment]
Thanks for following through. I noticed it but was treading lightly since .NET Framework gets weird in Unity.
