### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by storms-lab** [microsoft/MSBuildForUnity#68]
It seems like this project should work with Unity on Mac, but it does not currently. I get the following errors when trying to open the SimpleNuGetDependency.Unity project.

![image](https://user-images.githubusercontent.com/51679664/69571207-84bde980-0f8f-11ea-953a-36168228a544.png)

**Comment by andreiborodin** [comment]
@storms-lab, I went ahead and fixed this, would be great if you tried it out!

**Comment by andreiborodin** [comment]
I will close the issue, and feel free to re-open or file a new issue if needed.
